### ISSUE TITLE
Fix summarize_transcript@3: changed command

### ISSUE THREAD

**Issue by gcoter** [gcoter/extract-keywords-from-youtube-videos#1]
For some reason, even after a complete `dvc repro`, `dvc status` will still show that:
```
summarize_transcript@3:
        changed command
```

In `dvc.lock`, this stage can be found here: https://github.com/gcoter/extract-keywords-from-youtube-videos/blob/87b894b4e3dd34bbe74e9d1550df151fe6843a7a/dvc.lock#LL1977C3-L1991C16
```
  summarize_transcript@3:
    cmd: "python3 src/summarize_transcript.py --input_transcript_file_path \"data/transcripts/Lyon
      Data Science Open Street Map 24-10-2017.txt\" --output_summary_file_path \"
      data/summaries/Lyon Data Science Open Street Map 24-10-2017.txt\"\n"
    deps:
    - path: data/transcripts/Lyon Data Science Open Street Map 24-10-2017.txt
      md5: d00f09dad4c26038ef8bcdf5e07bda90
      size: 87983
    - path: src/summarize_transcript.py
      md5: 8d2a104b345ad2d2b148d3cab6f03db3
      size: 1543
    outs:
    - path: data/summaries/Lyon Data Science Open Street Map 24-10-2017.txt
      md5: b397d7cad6ec32ba98b21f1a852395c8
      size: 660
```

It does not look different from the other stages which work correctly.
